# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gecken
tagline:          Mati suri di taman
url:              http://getpoole.com
paginate:         1
baseurl:          ""
author:
  name:           Novendriono
  url:            https://twitter.com/novendriono
  email:          novendriono@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
